language: cpp
compiler:
    - gcc

sudo: false

addons:
    apt:
        packages:
        - gcc-multilib

install:
    - | 
      (
          cd .libs/libffcall &&
          mkdir ./build
          chmod +x ./build.sh && 
          ./build.sh ./build ./repo --host=i486-unknown-linux  CC="gcc -m32" CXX="g++ -m32"
      )

script: 
    - exit 0

